# Chapter 1: Tensors

## 1.1 What is a Tensor?

An $n$-dimensional array. For a matrix $\mathbf{A} \in \mathbb{R}^{m \times n}$:

$$\mathbf{A} = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix}$$

## Exercise

1. What does `id(x.storage()) == id(y.storage())` tell you?
2. Try `y = x.clone()` — does storage id change?

# What is a Tensor?


In [1]:
import torch as tr # library

## Scalar

A scalar is a 0D number. It is just a single number.

In [2]:
s = tr.tensor([2.]) # scalar
print(s.item())

2.0


## Vector 

A vector is 1D number list. It is a list of any length of numbers.

In [3]:
v = tr.tensor([2.,3.]) # scalar
print(v)
print("length:", len(v)) # number of elements in the vector

tensor([2., 3.])
length: 2


In [4]:
print("length:", v.shape) # shape of a vector

length: torch.Size([2])


In [5]:
print("norm:", tr.norm(v))

norm: tensor(3.6056)


In [6]:
k = 3
print("vector", v)
print("scalar multiply", k*v)

vector tensor([2., 3.])
scalar multiply tensor([6., 9.])


* Shape of a vector
* Norm of a vector
* Unit vector 
* Scalar multiplication

* Add two vectors
* Dot product of two vectors
* Cosine similarity of two vectors

## Matrix

In [7]:
m = tr.tensor([[1.,2.,3.],[2.,3.,4.]]) # matrix as a list of row vectors.
print(m.numpy())

[[1. 2. 3.]
 [2. 3. 4.]]


In [8]:
print(m.shape) # The number of row vectors = number of rows, 
# The number of element is each row vector = number of columns

torch.Size([2, 3])


* Add/Subtract two matrices
* Multiply a matrix by a scalar
* Multiplication of two matrices
* Hadamard Product of two matrices

In [9]:
m1 = tr.tensor([[1.,2.,3.],[2.,3.,4.]]) # matrix 1
m2 = tr.tensor([[1.,2.,3.],[2.,3.,4.]]) # matrix 2
m3 = tr.tensor([[1.,2.,3.],[2.,3.,4.],[5.,6.,7.]]) # matrix 2

print(m1)
print(m1+m2) # matrix addition
print(m1-m2) # matrix addition
print(m1@m3) # matrix multiplication
print(m1*m2) # hadamard product
print(m1.T)

tensor([[1., 2., 3.],
        [2., 3., 4.]])
tensor([[2., 4., 6.],
        [4., 6., 8.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[20., 26., 32.],
        [28., 37., 46.]])
tensor([[ 1.,  4.,  9.],
        [ 4.,  9., 16.]])
tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])


* M = A@B 
* M_ij = dot product of (ith row of A) and (jth column of B)
* row vectors of A should have the same length as column vectors of B
* number of columns of A = number of rows of B
* A (mxn) @ B (p,q) - then A @ B is possible iff n = p

### Matrix with Vector

In [10]:
v1 = tr.tensor([1.,2.,3.]) # 1D vector (3)
v2 = tr.tensor([[1.,2.,3.]]) # Row vector - matrix with 1 row = vector (1,3)
v3 = tr.tensor([[1.],[2.],[3.]]) # Column vector - matrix with 1 column = vector (3,1)

# print(v1)
print(v1.shape)
# print(v2)
print(v2.shape)
# print(v3)
print(v3.shape)
print(v2.T.shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])
torch.Size([3, 1])


In [11]:
m1 = tr.tensor([[1.,2.,3.],[2.,3.,4.]]) # matrix 1 = (2,3)
v1 = tr.tensor([1.,2.,3.]) # 1D vector (3)
v2 = tr.tensor([[1.,2.,3.]]) # Row vector - matrix with 1 row = (1,3)
v3 = tr.tensor([[1.],[2.],[3.]]) # Column vector - matrix with 1 column = (3,1)

print(m1@v1)
# print(m1@v2)
print(m1@v3)

tensor([14., 20.])
tensor([[14.],
        [20.]])


In [12]:
m1 = tr.tensor([[1.,2.,3.],[2.,3.,4.]]) # matrix 1 = (2,3)
v1 = tr.tensor([1.,2.,3.]) # 1D vector (3)
v3 = tr.tensor([[1.],[2.],[3.]]) # Column vector - matrix with 1 column = (3,1)

print((m1@v1).shape)
print((m1@v3).shape)

print(m1@v3+2.0) # broadcasting

torch.Size([2])
torch.Size([2, 1])
tensor([[16.],
        [22.]])


### Tensors (nD)

In [13]:
t = tr.ones([3,4,5,9,10,3,5,6])
print(t.shape)

torch.Size([3, 4, 5, 9, 10, 3, 5, 6])


In [ ]:
# broadcasting

t1 = tr.ones([4,6,1,3,6,1]) # 4,6,4,3,6,9
t2 = tr.ones([4,6,4,3,1,9]) # 4,6,4,3,6,9

# either they are equal or one of them has to be 1

print((t1+t2).shape)

torch.Size([4, 6, 4, 3, 1, 9])


In [25]:
t1 = tr.ones([1])
print(t1)
print(t1.shape)
t2 = tr.ones([1,2])
print(t2)
print(t2.shape)
print(t1+t2)

tensor([1.])
torch.Size([1])
tensor([[1., 1.]])
torch.Size([1, 2])
tensor([[2., 2.]])
