* A vector is 1D tensors
* A matrix is 2D tensors.
* What about nD tensors?

In [1]:
import torch as tr

In [2]:
v = tr.tensor([1.,2.,3.])
m = tr.tensor([[1.,2.,3.],[1.,2.,3.]])
rp = tr.tensor([[[1.,2.,3.],[1.,2.,3.]],[[1.,2.,3.],[1.,2.,3.]],[[1.,2.,3.],[1.,2.,3.]],[[1.,2.,3.],[1.,2.,3.]]])

In [3]:
print(v.shape)
print(m.shape)
print(rp.shape)

torch.Size([3])
torch.Size([2, 3])
torch.Size([4, 2, 3])


In [4]:
t =tr.ones([4,3,1,4,5,1,6])
print(t.shape)

torch.Size([4, 3, 1, 4, 5, 1, 6])


In [24]:
# Broadcasting (what are the rules of broadcasting)

t1 =tr.ones([4,3,1,4,5,9,6]) # [x0, x1, ..., xn]
t2 =tr.ones([4,3,3,4,5,1,6]) # [y0, y1, ..., yn]

print((t1*t2).shape)

# xi = yi or atleast of xi/yi should be 1.

torch.Size([4, 3, 3, 4, 5, 9, 6])


In [ ]:
t1 = tr.ones([1,2]) # row vector -> extended along the other row 2 -> 2x2 matrix
print(t1)
t2 = tr.ones([2,1]) # column vector -> extended along the other column 2 -> 2x2 matrix
print(t2)
print(t1+t2)

tensor([[1., 1.]])
tensor([[1.],
        [1.]])
tensor([[2., 2.],
        [2., 2.]])


In [ ]:
t = [[1.,1.,1.],[1.,1.,1.],[1.,1.,1.]]

In [50]:
x = tr.tensor([[[1,2,3],
               [4,5,6],[5,6,7]],[[1,2,3],
               [4,5,6],[5,6,7]]]) # (2,3,3)
print(x.shape)
y = tr.sum(x, dim = 2, keepdims = True) # (2,3)
print(y.shape) 

torch.Size([2, 3, 3])
torch.Size([2, 3, 1])


In [58]:
a = tr.tensor([[1,2],[3,4]]) # (2,2)
b = tr.tensor([[3],[4]]) # (2,1)
print(tr.cat([a,b], dim = 1).shape)

torch.Size([2, 3])


In [61]:
x = tr.tensor([1,2,3])
x.unsqueeze(0).expand([4,3]).shape

torch.Size([4, 3])

In [62]:
x = tr.tensor([1, 2, 3], dtype=tr.float32)
y = tr.tensor([4, 5, 6], dtype=tr.float32)
print(tr.outer(x,y))

tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])


In [68]:
tr.tensor((2,2)).shape

torch.Size([2])